### ISSUE TITLE
Missing arm64 support

### ISSUE THREAD

**Issue by tibeer** [mattermost-community/mattermost-plugin-jitsi#247]
**Mattermost Version**
9.7.1

**Plugin Version**
2.0.1

**Describe the issue**
After installing the plugin it cannot be enabled.

**Server Error Logs**
N/A

**Google Chrome Error Logs**
N/A

**Screenshots**
<img width="978" alt="image" src="https://github.com/mattermost-community/mattermost-plugin-jitsi/assets/39375770/9c734a9d-5fc6-484a-bab8-b0f7af3e75b6">

**Additional context**
I know that ARM64 is officially still not supported by mattermost. I am using e.g. https://github.com/this-is-tobi/multiarch-mirror/pkgs/container/mirror%2Fmattermost based on the discussion in this issue: https://github.com/mattermost/mattermost/issues/23387
If arm64 is out of scope for this plugin, I am fine with that, too :)

**Comment by vokey** [comment]
Before the maintainer team releases an ARM bundle, building an ARM binary ourselves might be a solution.
```
cd server && env CGO_ENABLED=0 GOOS=linux GOARCH=arm64 $(GO) build $(GO_BUILD_FLAGS) $(GO_BUILD_GCFLAGS) -trimpath -o dist/plugin-linux-arm64
```
And there is an ARM arch build script in the Makefile.

**Comment by tibeer** [comment]
For everybody else with the same issue: Instructions on how to build it on your own

1. check out release-2.0.1. branch
2. Change the `docker-make` file and add the platform like this:

```sh
#!/bin/bash

set -ex
docker build --platform linux/amd64 -t mattermost-plugin-jitsi-builder .
docker run --rm -it --platform linux/amd64 -v $(pwd):/src -w /src mattermost-plugin-jitsi-builder make "$@"
```

3. Change the `Makefile` by replacing all go build commands with only the arm64 one:

```sh
## Builds the server, if it exists, including support for multiple architectures.
.PHONY: server
server:
ifneq ($(HAS_SERVER),)
        mkdir -p server/dist;
        cd server && env GOOS=linux GOARCH=arm64 $(GO) build $(GO_BUILD_FLAGS) -o dist/plugin-linux-arm64;
endif
```

4. Run the `docker-make` file and prepare to wait for a very long time. If you receive an error like "no such linter revive", re-run the script but this time with the parameter dist: `./docker-make dist`
5. The plugin will be available in the new `dist` folder.
6. Extract the tag.gz file and change the following two files:

    - `plugin.json`
    - `webapp/dist/main.js`

    Both need to be extended with the new arm information.

    For `plugin.json`
    
    ```json
        "server": {
            "executables": {
                "linux-amd64": "server/dist/plugin-linux-amd64",
                "linux-arm64": "server/dist/plugin-linux-arm64",
                "darwin-amd64": "server/dist/plugin-darwin-amd64",
                "windows-amd64": "server/dist/plugin-windows-amd64.exe"
            }
        },
    ```
    
    For `webapp/dist/main.js`:
    
    ```json
    "executables": {\n            "linux-amd64": "server/dist/plugin-linux-amd64",\n            "linux-arm64": "server/dist/plugin-linux-arm64",\n            "darwin-amd64": "server/dist/plugin-darwin-amd64",\n            "windows-amd64": "server/dist/plugin-windows-amd64.exe"\n        }
    ```

7. Create the tar file again with `tar czf jitsi_arm64.tar.gz assets public server webapp plugin.json`
8. Upload the file to your Mattermost installation. If you are in Kubernetes: Make sure to set the `nginx.ingress.kubernetes.io/proxy-body-size` to something bigger than 50m, as the tar file is around 53m.
